### ISSUE TITLE
Easier support for Raspberry Pi type deployments

### ISSUE THREAD

**Issue by nov1n** [alin23/lunarsensor#2]
When running this on a Raspberry Pi or similar, it would be convenient to have a configurable port or a common prefix (such as `/lunar/*`) for API endpoints to configure this route in a reverse proxy.

Can we support either of these options?

**Comment by alin23** [comment]
Hi @nov1n 

Sure thing, I added the `PORT` Makefile variable so you can now do something like:

```sh
make PORT=8080
```

**Comment by alin23** [comment]
Oh, that is not possible. I thought you said something about a reverse proxy.

You can run Caddy on port 80 in front of your other servers on the Pi, and point `/events` and `/ambient_light` to 8080 to allow Lunar to find the sensor.

**Comment by alin23** [comment]
I added support for this in **v6 beta 5** if you'd like to try it: https://f.lunar.fyi/ArnPeX/Lunar-6.0.0b5.dmg

There are three settings that affect where Lunar looks for the sensor:

- `sensorHostname` set by default to `lunarsensor.local`
- `sensorPort` set by default to `80`
- `sensorPathPrefix` set by default to `/`

For example, if you would like to have Lunar listen for sensor events at `homeassistant.local:8123/lunar/events` you would run the following commands:

```sh
defaults write fyi.lunar.Lunar sensorHostname homeassistant.local
defaults write fyi.lunar.Lunar sensorPort 8123
defaults write fyi.lunar.Lunar sensorPathPrefix /lunar
```

**Comment by nov1n** [comment]
That is exactly what I was looking for! I will try it out tomorrow and let you know how it goes :)

**Comment by nov1n** [comment]
Works like a charm 👍 When the sensor is not available (e.g. I'm not on my home network), will it switch to the last selected mode (e.g. location)?

**Comment by alin23** [comment]
> Works like a charm 

Great to hear! ^\_^

If Auto Mode is selected in Lunar, then yes, Lunar will switch to the next available adaptive mode.

**Comment by nov1n** [comment]
That's great. Thanks for picking this up so quickly. Lunar is truly a great piece of software. Looking forward to the release!

**Comment by nov1n** [comment]
This morning the sensor was no longer available:
![Screenshot 2023-03-12 at 08 55 09](https://user-images.githubusercontent.com/4356790/224531784-f02ac4ed-cb5e-4d19-9cb8-836e725926c3.png)

I confirmed the registries are correctly set:
```
❯ defaults find sensorHostname                                                                                                  8:58:58
Found 1 keys in domain 'fyi.lunar.Lunar': {
    sensorHostname = "raspberrypi.local";
}

~
❯ defaults find sensorPort                                                                                                      8:59:02
Found 1 keys in domain 'fyi.lunar.Lunar': {
    sensorPort = 8065;
}
```

Curling the sensor works:
```
❯ curl raspberrypi.local:8065/sensor/ambient_light                                                                              8:58:10
{"id":"sensor-ambient_light","state":"400 lx","value":400}
```

Restarted Lunar, but problem persisted.

Restarting my Mac fixed the issue, but I'm not sure what happened. Will let you know if it happens again.

**Comment by nov1n** [comment]
It happened again after restarting the lunarsensor server. It seems like once it fails to read once it's unable (or stops trying?) to reconnect again. However I'd expect that restarting the Lunar application should fix this, but it doesn't.

**Comment by alin23** [comment]
Try this beta: https://f.lunar.fyi/DBbUrZ/Lunar-6.0.0b5.dmg

There was a problem that made it not work correctly with reverse proxies. After the sensor server connection is closed, Lunar starts a reconnection logic that should check for the sensor every 10 seconds.

**Comment by nov1n** [comment]
That did not fix it for me. I had to restart my Mac for the sensor to become available again.

**Comment by alin23** [comment]
That means it was most likely a network error. This version worked fine for me and 3 other users ¯\_(ツ)_/¯

**Comment by nov1n** [comment]
You were right. Some strange behavior with Docker + ipv6. FYI I noticed the Makefile does not work on Linux because `sudo -E` behaves differently.

**Comment by alin23** [comment]
Thanks for letting me know, it should be fixed for Linux as well now.

**Comment by nov1n** [comment]
When using the server with a Zigbee sensor that publishes readings at 10s intervals the change of brightness can be quite abrupt and noticeable. Is there any way to transition this over a short duration to make it less sudden?
