### ISSUE TITLE
Run on boot

### ISSUE THREAD

**Issue by RitwikGupta** [alin23/lunarsensor#5]
Is there any easy way to run this server on boot?
I have this set up on a Raspberry Pi Zero, but the power supply to it is not always reliable. It would be awesome to have this run as a daemon on boot.

**Comment by RitwikGupta** [comment]
I solved this via a systemd service. Perhaps there's a better way to do this, but for anyone else looking:

Create a script that launches the Lunar sensor server:
`launch_lunarserver.sh`
```
#!/bin.bash
source /home/pi/lunar-venv/bin/activate
cd /home/pi/lunarsensor
make run
```

Create a systemd service
`/etc/systemd/system/lunarsensor.service`
```
[Unit]
Description=Start lunar sensor server.

[Service]
Type=simple
ExecStart=/bin/bash /home/pi/launch_lunarserver.sh

[Install]
WantedBy=multi-user.target
```

Set permissions on the service, enable it, and start it
```
sudo chmod 644 /etc/systemd/system/lunarsensor.service
systemctl enable lunarsensor.service
sudo service lunarsensor start
```

**Comment by alin23** [comment]
Yes, that systemd service is a good way to do this on Linux. I leave this for everyone to do it their way since it's just a Python server that can run on any OS.
